server:
  port: ${port:9772}

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
  jpa:
    hibernate:
      ddl-auto: update
      default_schema: "h"